{% set name = "mockito" %}
{% set version = "1.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kaste/mockito-python/archive/{{ version }}.tar.gz
  sha256: fe0614d07bf0f762f9b0e7b7183788e80941950315f58dfa2d405415afc9e65a

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - mockito
  requires:
    - pip
    - pytest
    - numpy
    - python {{ python_min }}
  source_files:
    - tests/
  commands:
    - pip check
    - pytest tests

about:
  home: https://github.com/kaste/mockito-python
  summary: Spying framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vnlitvinov
